services:
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama-docker

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

  aisel-script:
    build:
      context: ./data-sources/aisel
      dockerfile: DOCKERFILE    # Specify the Dockerfile for app1
    container_name: aisel-container
    volumes:
      - ./data-sources/aisel/aisel_crawler.py:/usr/src/app/aisel_crawler.py
    entrypoint: ["/bin/sh", "-c", "echo '0 16 * * * python /usr/src/app/aisel_crawler.py' > /etc/crontabs/root && crond -f"]
    networks:
      - ollama-docker

  arxiv-script:
    build:
      context: ./data-sources/arxiv
      dockerfile: DOCKERFILE    # Specify the Dockerfile for app1
    container_name: arxiv-container
    volumes:
      - ./data-sources/arxiv/arxiv_crawler.py:/usr/src/app/arxiv_crawler.py
    entrypoint: ["/bin/sh", "-c", "echo '0 17 * * * python /usr/src/app/arxiv_crawler.py' > /etc/crontabs/root && crond -f"]
    networks:
      - ollama-docker

  pubmed-script:
    build:
      context: ./data-sources/pubmed
      dockerfile: DOCKERFILE    # Specify the Dockerfile for app1
    container_name: pubmed-container
    volumes:
      - ./data-sources/pubmed/pubmed_crawler.py:/usr/src/app/pubmed_crawler.py
    entrypoint: ["/bin/sh", "-c", "echo '0 18 * * * python /usr/src/app/pubmed_crawler.py' > /etc/crontabs/root && crond -f"]
    networks:
      - ollama-docker


networks:
  ollama-docker:
    external: false