# Use a base Python image
FROM python:3.10-slim

# Update the package list and install cron and nano
RUN apt-get update && apt-get -y install cron && apt-get -y install nano

# Set the working directory
WORKDIR /usr/src/app

# Copy the crontab file and Python script into the container
COPY data-sources/pubmed/crontab /etc/cron.d/crontab
COPY data-sources/pubmed/pubmed_crawler.py /usr/src/app/pubmed_crawler.py
COPY ./database.py /usr/src/app/database.py

COPY /.env /usr/src/app/.env

# Install any required dependencies (if you have a requirements.txt file)
COPY data-sources/pubmed/requirements_pubmed.txt .
RUN pip install --no-cache-dir -r requirements_pubmed.txt

# Set proper permissions for the crontab file
RUN chmod 0644 /etc/cron.d/crontab

# Register the crontab file with the cron service
RUN /usr/bin/crontab /etc/cron.d/crontab

# Run cron as the main process of the container
CMD ["cron", "-f"]
