# Use a base Python image
FROM python:3.10-slim

# Update the package list and install cron
RUN apt-get update && apt-get -y install cron && apt-get -y install nano

# Set the working directory
WORKDIR /usr/src/app

# Copy the crontab file and Python script into the container
COPY telegram_update/crontab /etc/cron.d/crontab
COPY telegram_update/updater.py /usr/src/app/updater.py
COPY telegram_update/helper.py /usr/src/app/helper.py
COPY ./database.py /usr/src/app/database.py

COPY /.env /usr/src/app/.env

# Install required Python dependencies
COPY telegram_update/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Set proper permissions for the crontab file
RUN chmod 0644 /etc/cron.d/crontab

# Register the crontab file with the cron service
RUN /usr/bin/crontab /etc/cron.d/crontab

# Run cron as the main process of the container
CMD ["cron", "-f"]